### ISSUE TITLE
Browserify seems to load leveldown

### ISSUE THREAD

**Issue by rh0** [Level/level-browserify#30]
Apologies if I am misunderstinding something basic here, however I cannot seem to get level-browserify to load level-js when using browserify.  As a simple test I was using something like:
```javascript
var level = require('level-browserify')

if(typeof level.destroy !== 'function') {
  console.log('Bummer, level.destroy is not a function')
}
else {
  console.log('Huzzah!')
}
```
After compilation with browserify, `.destroy` is never found to be a function (a sign that level-js is not used). I see that level-browserify has a browser field in package.json pointing at browser.js, but this does not seem to be respected. I can add a browser field to my own package.json, along the lines of:
```json
  "browser": {
    "level-browserify": "level-js"
  }
```
After which level-js seems to load correctly, but this feels blatantly wrong.

_Edit:_
_browserify v15.0.0_
_level-browserify v1.1.1_

**Comment by ralphtheninja** [comment]
I can reproduce with `v1.1.1` using `browserify@15.0.0`. It seems to work well with `v1.1.2` so I suggest you upgrade. We're about to release `v2.0.0` shortly, once `level-js@3` is released.
